### ISSUE TITLE
Make Trac read-only, possibly replace by a static dump

### ISSUE THREAD

**Issue by mgol** [jquery/infrastructure-puppet#10]
A while ago, we made jQuery Core Trac instance (https://bugs.jquery.com/) read-only, making the only still fully functional Trac instance to be the jQuery UI one (https://bugs.jqueryui.com/). With jQuery UI being maintained in a very limited way nowadays, it doesn't make sense to maintain a full separate bug tracker just for this project; other projects are using GitHub issues.

We want to enable GitHub issues for jQuery UI and make the UI Trac read-only. In the future, we can consider replacing Trac with a static dump of all its pages if that makes maintenance easier.

I'm not 100% sure what we did for Core but I think we mostly blocked account registration and removed all existing accounts as with no accounts the site is essentially read-only. @rjollos can you help with doing the same for UI? I'm not sure if it was you or someone else involved with the changes for the Core Trac.

**Comment by Krinkle** [comment]
@timmywil expressed interest in helping with this. Let me know if you need any help with access.

To access the current Trac server, send a PR adding your ssh key to `/modules/user/manifests/virtual.pp` and `/modules/user/manifests/sysadmins.pp` against this (private) infra repo.

The provision of the new static server would take place in public at https://github.com/jquery/infrastructure-puppet, but Taavi and myself can help with that if needed. I suggest publishing the export to a Git repo, that we can then sling up onto a static server.

**Comment by timmywil** [comment]
Sites are ready to deploy at https://github.com/jquery/bugs.jquery.com and https://github.com/jquery/bugs.jqueryui.com. Note that some redirects will need to be deactivated.

**Comment by Krinkle** [comment]
> Note that some redirects will need to be deactivated.

@timmywil Which ones? I propose to do bugs.jqueryui.com first so let me know which redirects needs to be removed.

> Sites are ready to deploy at https://github.com/jquery/bugs.jquery.com and https://github.com/jquery/bugs.jqueryui.com. 

Could you update the deploy job to push the result to a branch? See [qunitjs.com workflow](https://github.com/qunitjs/qunitjs.com/blob/251cc16aeea05b163e4e080e646f4b8756aad035/.github/workflows/github-pages.yaml#L36) for example. This way we have a copy of the static site HTML permanently, rather than dependent on current OS/Node/npm packages working exactly in the future to reproduce the site. It also has as a bonus the ability to diff changes (if any) in the future, and means I can securely deploy as a simple static site that pulls from a public repo (no credentials, no push) without executing any code on the server.

I will include a webhook the org-wide jquery hook since it's easy to do, so that updates are immediately live, same as GitHub Pages.

**Comment by timmywil** [comment]
> Which ones?

Any and all related to these sites. I don't think I have access to see the list, but redirects will no longer be necessary. I know that https://bugs.jquery.com/newticket currently redirects to core github (well, it used to. It's actually broken now and goes to a 404 page). That will no longer be necessary. It may just be `/newticket` on both sites, but it'd be good to double check.

> Could you update the deploy job to push the result to a branch?

Will do

**Comment by Krinkle** [comment]
> > Which ones?
> 
> Any and all related to these sites. I don't think I have access to see the list, but redirects will no longer be necessary. I know that https://bugs.jquery.com/newticket currently redirects to core github (well, it used to. It's actually broken now and goes to a 404 page). That will no longer be necessary. It may just be `/newticket` on both sites, but it'd be good to double check.

In Cloudflare for bugs.jqueryui.com, I see no redirect rules.

On the old Trac server, it has a local Nginx proxy configured in the private repo at https://github.com/jquery/infrastructure/blob/33557055ee/modules/jquery/templates/nginx/trac.conf.erb#L35. That seems to define `/newticket` as the only redirect.

In any event, if we're only worried about _disabling_ redirects, then we don't have to look any further. When we switch the domain to a new server serving a static site, the old server and any redirects it may have naturally go away from the public POV.

**Comment by timmywil** [comment]
Trac sites are now being deployed to branches. I made the repos public. I was just cautious when I first started, but everything in there is public already.

Edit: The workflow would require new SSH keys in order to clone the private repo in GH actions. I started doing that and then realized they should just be public.

**Comment by Krinkle** [comment]
@timmywil I've switched over bugs.jqueryui.com. It looks like `pagefind.js` is missing from the latest few builds. This wasn't visible on the github.io preview because that was still sourced from an earlier commit, based on the now-non-existant "action".

To confirm whether bugs.jquery.com is affected as well, I've updated the Pages settings at https://github.com/jquery/bugs.jquery.com/ from Action to Branch: gh-pages. The latest version does appear to be working fine, there. Something appears to be up with the jqueryui archive.

No rush. We'll catch up when you're back in two weeks :)

**Comment by Krinkle** [comment]
@timmywil @rjollos I've powered off the `trac.ops.jquery.net` droplet. I'll give it two weeks before deleting. Let me know if you'd like it back on for any thing!

**Comment by rjollos** [comment]
> I'll give it two weeks before deleting. Let me know if you'd like it back on for any thing!

Thanks, that shouldn't be a problem.

**Comment by rjollos** [comment]
> @timmywil @rjollos I've powered off the `trac.ops.jquery.net` droplet. I'll give it two weeks before deleting. Let me know if you'd like it back on for any thing!

Thanks, that shouldn't be a problem.

**Comment by timmywil** [comment]
pagefind issue on the ui site should be fixed next deployment. Turns out I forgot to update pagefind.

**Comment by timmywil** [comment]
Looks fixed. Can probably close this ticket now.

**Comment by Krinkle** [comment]
I haven't deleted the droplet and Tarsnap backups yet.

**Comment by Krinkle** [comment]
* Deleted  backups at Tarsnap for `trac.ops.jquery.net`.
* Deleted `trac.ops.jquery.net` droplet.
* Deleted DNS entry for `trac.ops.jquery.net`.
* Archived Puppet provisioning for Trac.
