### ISSUE TITLE
Ensure we can reset pw on WordPress blogs

### ISSUE THREAD

**Issue by Krinkle** [jquery/infrastructure-puppet#15]
About the on-going host refresh for WP (ref https://github.com/jquery/infrastructure-puppet/issues/6), @timmywil wrote:

> Is outgoing email working for pw reset and comment approval etc?

**Comment by supertassu** [comment]
Has this been working before? If so, could someone send me a sample mail with the headers included?

I don't see any configuration regarding mail either in this repository or in `wp-config.php`, nor is there any mail daemon running directly on the old WP hosts as far as I can see.

In the modern internet email is usually sent via some relays, since mails directly from common VPS provider IP spaces usually ends up being marked as spam.

**Comment by timmywil** [comment]
I don't think it ever worked. We no longer need it for comment approval (we've turned off comments). Now that we've updated the admin email from john's email to the infra team email, it's less necessary. It would still be nice for password reset or profile email changes, but those could be done manually in the DB if hooking up email is too cumbersome.

**Comment by Krinkle** [comment]
Maybe an alternative here would be to document the recommended way to change a password from the CLI.
